name: Keep Alive

on:
  schedule:
    # Run on the 1st and 15th of each month at 00:00 UTC
    # Only needs to run within 60 days to prevent workflow deactivation
    - cron: "0 0 1,15 * *"
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
